In [22]:
region = "Pacific"

In [23]:
import pandas as pd
from sqlalchemy import create_engine

In [24]:
import sqlalchemy
import psycopg2
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:Peter@1947@localhost/VotingProject')

In [25]:
combined_df = pd.read_sql("combined_by_county",engine)
combined_df.head()

,level_0,index,state,county,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,...,dem2012,rep2012,oth2012,tot2012,dem2016,rep2016,oth2016,tot2016,region,electoral_votes
0,0,0,Alabama,Autauga,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,...,6363.0,17379.0,190.0,23932.0,5936.0,18172.0,865.0,24973.0,Southeast,9.0
1,1,1,Alabama,Baldwin,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,...,18424.0,66016.0,898.0,85338.0,18458.0,72883.0,3874.0,95215.0,Southeast,9.0
2,2,2,Alabama,Barbour,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,...,5912.0,5550.0,47.0,11509.0,4871.0,5454.0,144.0,10469.0,Southeast,9.0
3,3,3,Alabama,Bibb,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,...,2202.0,6132.0,86.0,8420.0,1874.0,6738.0,207.0,8819.0,Southeast,9.0
4,4,4,Alabama,Blount,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,...,2970.0,20757.0,279.0,24006.0,2156.0,22859.0,573.0,25588.0,Southeast,9.0

In [26]:
combined_df.columns

Index(['level_0', 'index', 'state', 'county', 'total_population', 'cvap',
       'white_pct', 'black_pct', 'hispanic_pct', 'nonwhite_pct',
       'foreignborn_pct', 'female_pct', 'age29andunder_pct',
       'age65andolder_pct', 'median_hh_inc', 'clf_unemploy_pct', 'lesshs_pct',
       'lesscollege_pct', 'lesshs_whites_pct', 'lesscollege_whites_pct',
       'rural_pct', 'ruralurban_cc', 'county_code', 'land_area', 'CBSA',
       'metro_name', 'dem2000', 'rep2000', 'oth2000', 'tot2000', 'dem2004',
       'rep2004', 'oth2004', 'tot2004', 'dem2008', 'rep2008', 'oth2008',
       'tot2008', 'dem2012', 'rep2012', 'oth2012', 'tot2012', 'dem2016',
       'rep2016', 'oth2016', 'tot2016', 'region', 'electoral_votes'],
      dtype='object')

In [27]:
if region != "all":
    combined_df = combined_df.loc[combined_df["region"] == region,:]
combined_df.head()

,level_0,index,state,county,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,...,dem2012,rep2012,oth2012,tot2012,dem2016,rep2016,oth2016,tot2016,region,electoral_votes
157,157,157,California,Alameda,1605217.0,1040380.0,32.630915,11.015271,22.555829,67.369085,...,469684.0,108182.0,17776.0,595642.0,514842.0,95922.0,43502.0,654266.0,Pacific,55.0
158,158,158,California,Alpine,1184.0,895.0,67.905405,0.844595,7.770270,32.094595,...,389.0,236.0,28.0,653.0,334.0,217.0,51.0,602.0,Pacific,55.0
159,159,159,California,Amador,36963.0,30240.0,79.636393,2.326651,13.045478,20.363607,...,6830.0,10281.0,538.0,17649.0,6004.0,10485.0,1245.0,17734.0,Pacific,55.0
160,160,160,California,Butte,223877.0,170635.0,73.432286,1.464644,15.411588,26.567714,...,42669.0,44479.0,3604.0,90752.0,41567.0,45144.0,8853.0,95564.0,Pacific,55.0
161,161,161,California,Calaveras,44787.0,35475.0,82.293969,0.571594,11.226472,17.706031,...,8670.0,12365.0,751.0,21786.0,7944.0,13511.0,1681.0,23136.0,Pacific,55.0

In [28]:
data_df = combined_df[["nonwhite_pct","rep2016","dem2016"]]
data_df.head()

     nonwhite_pct  rep2016   dem2016
157     67.369085  95922.0  514842.0
158     32.094595    217.0     334.0
159     20.363607  10485.0    6004.0
160     26.567714  45144.0   41567.0
161     17.706031  13511.0    7944.0

In [29]:
data_df.dtypes

nonwhite_pct    float64
rep2016         float64
dem2016         float64
dtype: object

In [30]:
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
group_names = ["0-10", "10-20", "20-30", "30-40", "40-50",
               "50-60", "60-70", "70-80", "80-90", "90-100"]
data_df["ind"] = pd.cut(data_df["nonwhite_pct"], bins, labels=group_names)
data_df["bin"] = pd.cut(data_df["nonwhite_pct"], bins, labels=group_names)
data_df.head(25)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     nonwhite_pct   rep2016    dem2016    ind    bin
157     67.369085   95922.0   514842.0  60-70  60-70
158     32.094595     217.0      334.0  30-40  30-40
159     20.363607   10485.0     6004.0  20-30  20-30
160     26.567714   45144.0    41567.0  20-30  20-30
161     17.706031   13511.0     7944.0  10-20  10-20
162     63.105660    3551.0     2661.0  60-70  60-70
163     54.438071  115956.0   319287.0  50-60  50-60
164     36.922687    5134.0     3485.0  30-40  30-40
165     21.273770   49247.0    36404.0  20-30  20-30
166     69.240313  124049.0   141341.0  60-70  60-70
167     46.936660    5788.0     3065.0  40-50  40-50
168     24.617183   18373.0    33200.0  20-30  20-30
169     88.068700   12704.0    32667.0  80-90  80-90
170     35.976209    4248.0     3155.0  30-40  30-40
171     63.965377  129584.0    98689.0  60-70  60-70
172     66.367853   18093.0    13617.0  60-70  60-70
173     27.740496   10599.0    11496.0  20-30  20-30
174     33.945844    7574.0     2224.0  30-40  30-40
175     73.274877  769743.0  2464364.0  70-80  70-80
176     64.211755   23357.0    17029.0  60-70  60-70
177     28.145266   21771.0   108707.0  20-30  20-30
178     18.498158    5185.0     3122.0  10-20  10-20
179     33.624684   10888.0    22079.0  30-40  30-40
180     70.521243   28725.0    37317.0  70-80  70-80
181     22.351378    2696.0      877.0  20-30  20-30

In [31]:
by_bin = data_df.groupby(["ind"])
rep_tot = by_bin["rep2016"].sum()
dem_tot = by_bin["dem2016"].sum()
summary = pd.DataFrame({"bins":bins,"Rep":rep_tot, "Dem": dem_tot})
summary

ValueError: zero-size array to reduction operation minimum which has no identity

In [ ]:
binList = group_names
repValues = list(summary["Rep"])
demValues = list(summary["Dem"])
binList