In [6]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
import sqlalchemy
import psycopg2
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:Peter@1947@localhost/VotingProject')

In [8]:
combined_df = pd.read_sql("combined_by_county",engine)
combined_df.head()

,level_0,index,state,county,total_population,cvap,white_pct,black_pct,hispanic_pct,nonwhite_pct,...,dem2012,rep2012,oth2012,tot2012,dem2016,rep2016,oth2016,tot2016,region,electoral_votes
0,0,0,Alabama,Autauga,55049.0,40690.0,75.683482,18.370906,2.572254,24.316518,...,6363.0,17379.0,190.0,23932.0,5936.0,18172.0,865.0,24973.0,Southeast,9.0
1,1,1,Alabama,Baldwin,199510.0,151770.0,83.178788,9.225603,4.366698,16.821212,...,18424.0,66016.0,898.0,85338.0,18458.0,72883.0,3874.0,95215.0,Southeast,9.0
2,2,2,Alabama,Barbour,26614.0,20375.0,45.885624,47.888329,4.309762,54.114376,...,5912.0,5550.0,47.0,11509.0,4871.0,5454.0,144.0,10469.0,Southeast,9.0
3,3,3,Alabama,Bibb,22572.0,17590.0,74.765196,21.212121,2.223994,25.234804,...,2202.0,6132.0,86.0,8420.0,1874.0,6738.0,207.0,8819.0,Southeast,9.0
4,4,4,Alabama,Blount,57704.0,42430.0,87.657701,1.557951,8.727298,12.342299,...,2970.0,20757.0,279.0,24006.0,2156.0,22859.0,573.0,25588.0,Southeast,9.0